### ISSUE TITLE
Parse codes that return an empty row stops the while loop

### ISSUE THREAD

**Issue by hansen-simon** [pbock/zebra-crossing#5]
There are codes, that return an empty row when red with the zxing cli. 
The while loop for parsing the output lines stops at falsy values, therefore the empty line interrups the parsing.

**Comment by JensSpanier** [comment]
I ran into this problem today too. PR is open since almost 2 years. Can you look into this @pbock?

**Comment by pbock** [comment]
Sorry, that pull request completely passed me by. Thanks for your work, @hansen-simon, and the reminder, @JensSpanier. I’ve merged and published it. Crossing my fingers that everything works after not touching this project for six years.

**Comment by JensSpanier** [comment]
Updated the package and now it works like a charm. Thanks!
